#!/usr/bin/env zsh
# I am using zsh instead of bash.  I was having some troubles using bash

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd


