#!/bin/bash

file_path="/usr/share/X11/xorg.conf.d/40-libinput.conf"
section_identifier="libinput touchpad catchall"
option_to_add="        Option \"NaturalScrolling\" \"True\""

# Add or overwrite the naturalscrolling option in the specified section
sed -i "/^Section \"$section_identifier\"/,/^EndSection/ s/.*Option \"NaturalScrolling\".*/$option_to_add/" "$file_path"

echo "Option added or updated in $section_identifier section."

